export const Specialists = [
  { label: 'Cardiologist', value: 12},
  { label: 'Dermatologist', value: 24},
  { label: 'Endocrinologist', value: 22},
  {
    label: 'Gastroenterologist',
    value: 3,
  },
  { label: 'Hematologist', value: 5},
  { label: 'Neurologist', value: 23},
  { label: 'Gynecologist', value: 44},
  { label: 'Oncologist', value: 89},
  { label: 'Ophthalmologist', value: 92},

  {
    label: 'Otolaryngologist',
    value: 23,
  },
  { label: 'Pediatrician', value:33 },
  { label: 'Psychiatrist', value: 12},
  { label: 'Pulmonologist', value: 75},
  { label: 'Radiologist', value: 55},
  { label: 'Rheumatologist', value: 34},
  { label: 'Urologist', value: 9},
  { label: 'Allergist', value: 0},
  { label: 'Dentist', value: 13},
  { label: 'Dietitian', value: 14},
  { label: 'Nephrologist', value: 5},
  { label: 'Obstetrician', value: 68},
  { label: 'Orthopedist', value: 99},
];
